[package]
name = "sequisat"
version = "0.1.0"
edition = "2021"

[dependencies]
mathru = "0.15.4"
chrono = "0.4.38"
julian = "0.7"

ratatui = "0.29"
crossterm = "0.25"

env_logger = "0.10"
log = "0.4"

